"""Initial database schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-06-24 00:00:00.000000

This is the initial migration template.
Actual migration code will be auto-generated by Alembic.
"""

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    """Upgrade database schema"""
    pass


def downgrade() -> None:
    """Downgrade database schema"""
    pass
